<?php

return [
    'readiness_scores' => [
        'data_ownership' => env('ENTERPRISE_DATA_OWNERSHIP_SCORE', 54),
        'access_policy' => env('ENTERPRISE_ACCESS_POLICY_SCORE', 50),
        'resource_ownership' => env('ENTERPRISE_RESOURCE_OWNERSHIP_SCORE', 52),
        'governance' => env('ENTERPRISE_DATA_GOVERNANCE_SCORE', 56),
        'compliance' => env('ENTERPRISE_COMPLIANCE_SCORE', 46),
        'enterprise_audit' => env('ENTERPRISE_AUDIT_SCORE', 58),
    ],
    'ownership_domains' => [
        'personal' => [
            'description' => 'Resource is fully owned by one user.',
            'examples' => ['personal_mailbox', 'personal_api_key', 'personal_settings'],
        ],
        'organization' => [
            'description' => 'Resource is owned by the organization as an enterprise boundary.',
            'examples' => ['organization_domains', 'organization_reports', 'organization_audit_logs'],
        ],
        'shared' => [
            'description' => 'Resource has layered access across user, organization, workspace, team, and delegated roles.',
            'examples' => ['workspace_reports', 'team_resources', 'shared_mailboxes'],
        ],
    ],
    'resource_ownership_matrix' => [
        'mailboxes' => ['default_owner' => 'personal_or_organization', 'visibility' => 'owner_and_scoped_admins'],
        'domains' => ['default_owner' => 'organization', 'visibility' => 'owner_org_admin_security_admin'],
        'domain_pools' => ['default_owner' => 'organization_or_platform', 'visibility' => 'platform_and_org_admins'],
        'messages' => ['default_owner' => 'mailbox_owner', 'visibility' => 'mailbox_owner_and_policy_scoped_roles'],
        'attachments' => ['default_owner' => 'message_owner', 'visibility' => 'message_owner_and_policy_scoped_roles'],
        'api_keys' => ['default_owner' => 'user_organization_workspace_or_service', 'visibility' => 'key_owner_and_security_admin'],
        'audit_logs' => ['default_owner' => 'organization_or_platform', 'visibility' => 'owner_admin_security_compliance_roles'],
        'security_events' => ['default_owner' => 'organization_or_platform', 'visibility' => 'security_roles_and_owner'],
        'reports' => ['default_owner' => 'organization_or_workspace', 'visibility' => 'report_owner_and_scoped_admins'],
        'analytics' => ['default_owner' => 'organization_or_platform', 'visibility' => 'aggregate_only_for_authorized_roles'],
        'billing_resources' => ['default_owner' => 'organization_or_user', 'visibility' => 'owner_billing_admin'],
        'organization_settings' => ['default_owner' => 'organization', 'visibility' => 'owner_org_admin'],
        'workspace_resources' => ['default_owner' => 'workspace', 'visibility' => 'workspace_admin_and_scoped_members'],
        'team_resources' => ['default_owner' => 'team', 'visibility' => 'team_lead_and_scoped_members'],
    ],
    'access_policies' => [
        'direct_access' => 'Explicit access granted to a user, member, role, or service.',
        'inherited_access' => 'Access inherited from organization, workspace, team, or role membership.',
        'delegated_access' => 'Scoped access delegated by an owner or admin for defined responsibilities.',
        'temporary_access' => 'Time-bound access for support, incident, audit, or contractor workflows.',
        'emergency_access' => 'Break-glass access with strict audit, approval, and review requirements.',
    ],
    'boundaries' => [
        'user_boundary' => 'Personal account and identity scope.',
        'organization_boundary' => 'Enterprise account ownership, billing, governance, and security scope.',
        'workspace_boundary' => 'Department or operational area scope.',
        'team_boundary' => 'People and workflow responsibility scope.',
        'resource_boundary' => 'Specific mailbox, domain, API key, report, audit log, or billing object scope.',
        'audit_boundary' => 'Read, export, archive, and purge control scope for audit records.',
    ],
    'visibility_roles' => [
        'owner' => ['all_organization_resources', 'billing', 'audit_summary', 'security_summary'],
        'organization_admin' => ['members', 'workspaces', 'teams', 'reports', 'operational_summary'],
        'workspace_admin' => ['workspace_resources', 'workspace_members', 'workspace_reports'],
        'team_lead' => ['team_resources', 'team_members', 'team_activity_summary'],
        'member' => ['assigned_resources', 'own_activity', 'permitted_reports'],
        'guest' => ['explicitly_shared_resources'],
    ],
    'governance' => [
        'retention' => 'Organization-defined retention policies should override defaults only when legally and operationally approved.',
        'deletion' => 'Deletion should separate soft-delete, purge eligibility, legal hold, and audit retention.',
        'export' => 'Exports should be scoped, approved, auditable, and rate-limited.',
        'portability' => 'Portable exports should separate user-owned data from organization-owned data.',
        'classification' => 'Data should be classified by sensitivity, ownership, and retention requirement.',
        'lifecycle' => 'Lifecycle should cover creation, access, retention, export, deletion, archive, and purge.',
    ],
    'compliance' => [
        'gdpr' => 'Future design should support lawful basis, export, deletion, and auditability.',
        'data_subject_access' => 'DSAR flow must distinguish personal data from organization-owned operational data.',
        'right_to_delete' => 'Deletion must account for audit, security, billing, and legal retention requirements.',
        'data_export' => 'Exports must be scoped by ownership and access policy.',
        'auditability' => 'Sensitive access and export actions must be auditable.',
        'enterprise_compliance' => 'Enterprise compliance requires policy, evidence, retention, and access review readiness.',
    ],
    'resource_isolation' => [
        'soft_isolation' => ['advantage' => 'Low cost and fast to adopt.', 'disadvantage' => 'Weak enforcement story.'],
        'logical_isolation' => ['advantage' => 'Good SaaS default with policy and query scoping.', 'disadvantage' => 'Requires disciplined tests and reviews.'],
        'tenant_isolation' => ['advantage' => 'Stronger customer separation.', 'disadvantage' => 'Higher operational complexity.'],
        'dedicated_resource_isolation' => ['advantage' => 'Best enterprise isolation.', 'disadvantage' => 'Highest cost and maintenance burden.'],
    ],
    'delegated_access_roles' => [
        'temporary_admin' => 'Time-bound elevated administration for support or implementation.',
        'security_reviewer' => 'Read-focused security posture and event review.',
        'compliance_reviewer' => 'Read/export-focused compliance evidence review.',
        'billing_reviewer' => 'Billing and usage visibility without broad operational access.',
        'external_auditor' => 'Strictly scoped and time-bound audit evidence access.',
    ],
    'audit_access' => [
        'read' => ['owner', 'organization_admin', 'security_reviewer', 'compliance_reviewer', 'external_auditor'],
        'export' => ['owner', 'compliance_reviewer'],
        'archive' => ['owner', 'organization_admin'],
        'purge' => ['owner'],
    ],
    'data_exports' => [
        'user_export' => 'Personal data and user-owned resource export.',
        'organization_export' => 'Organization-owned operational data export.',
        'compliance_export' => 'Policy-approved compliance evidence export.',
        'audit_export' => 'Audit log export with approval and retention controls.',
    ],
    'api_ownership' => [
        'user_api_key' => 'Owned by a single user and scoped to personal resources.',
        'organization_api_key' => 'Owned by organization and scoped by policy.',
        'workspace_api_key' => 'Owned by workspace and scoped to workspace resources.',
        'service_api_key' => 'Owned by organization service account with strict lifecycle controls.',
    ],
];
