<?php

return [
    'readiness_scores' => [
        'governance' => env('ENTERPRISE_GOVERNANCE_SCORE', 57),
        'compliance' => env('ENTERPRISE_COMPLIANCE_READINESS_SCORE', 49),
        'policy_management' => env('ENTERPRISE_POLICY_MANAGEMENT_SCORE', 51),
        'access_review' => env('ENTERPRISE_ACCESS_REVIEW_SCORE', 47),
        'audit' => env('ENTERPRISE_AUDIT_READINESS_SCORE', 60),
        'incident_governance' => env('ENTERPRISE_INCIDENT_GOVERNANCE_SCORE', 53),
    ],
    'governance_domains' => [
        'identity_governance' => ['purpose' => 'Control enterprise identity ownership and lifecycle.', 'scope' => 'users, members, delegated roles', 'owner_role' => 'organization_owner', 'risk' => 'high', 'priority' => 'high'],
        'access_governance' => ['purpose' => 'Review and control access grants.', 'scope' => 'roles, resources, delegated access', 'owner_role' => 'security_reviewer', 'risk' => 'high', 'priority' => 'high'],
        'data_governance' => ['purpose' => 'Classify, retain, export, and delete data safely.', 'scope' => 'mailboxes, messages, reports, logs', 'owner_role' => 'compliance_reviewer', 'risk' => 'high', 'priority' => 'high'],
        'security_governance' => ['purpose' => 'Govern security posture and incident response.', 'scope' => 'sessions, devices, MFA, SSO, events', 'owner_role' => 'security_reviewer', 'risk' => 'high', 'priority' => 'high'],
        'audit_governance' => ['purpose' => 'Ensure audit trails are complete and exportable.', 'scope' => 'security, billing, API, policy, access changes', 'owner_role' => 'compliance_reviewer', 'risk' => 'medium', 'priority' => 'high'],
        'compliance_governance' => ['purpose' => 'Prepare compliance evidence and control coverage.', 'scope' => 'GDPR, SOC 2, ISO 27001, enterprise contracts', 'owner_role' => 'organization_owner', 'risk' => 'high', 'priority' => 'medium'],
        'retention_governance' => ['purpose' => 'Control retention, deletion eligibility, and legal holds.', 'scope' => 'mail data, audit logs, billing metadata, API logs', 'owner_role' => 'compliance_reviewer', 'risk' => 'medium', 'priority' => 'medium'],
        'export_governance' => ['purpose' => 'Control user, organization, compliance, and audit exports.', 'scope' => 'exports, approvals, evidence records', 'owner_role' => 'compliance_reviewer', 'risk' => 'medium', 'priority' => 'medium'],
        'incident_governance' => ['purpose' => 'Classify and manage enterprise incidents.', 'scope' => 'security, abuse, data, API, billing, provider incidents', 'owner_role' => 'security_reviewer', 'risk' => 'high', 'priority' => 'high'],
    ],
    'compliance_readiness' => [
        'gdpr' => ['data_subject_access', 'right_to_delete', 'data_export', 'retention_policy', 'auditability'],
        'soc2' => ['security', 'availability', 'confidentiality', 'processing_integrity', 'privacy'],
        'iso27001' => ['access_control', 'asset_management', 'logging', 'incident_response', 'risk_management'],
        'enterprise_contracts' => ['data_processing_terms', 'retention_commitments', 'export_commitments', 'audit_commitments', 'security_commitments'],
    ],
    'policies' => [
        'access_policy' => ['scope' => 'roles and resources', 'owner' => 'security_reviewer', 'enforcement_point' => 'future authorization layer', 'audit_required' => true, 'override_required' => true],
        'retention_policy' => ['scope' => 'data lifecycle', 'owner' => 'compliance_reviewer', 'enforcement_point' => 'future retention layer', 'audit_required' => true, 'override_required' => true],
        'export_policy' => ['scope' => 'data exports', 'owner' => 'compliance_reviewer', 'enforcement_point' => 'future export workflow', 'audit_required' => true, 'override_required' => true],
        'deletion_policy' => ['scope' => 'deletion and purge', 'owner' => 'organization_owner', 'enforcement_point' => 'future deletion workflow', 'audit_required' => true, 'override_required' => true],
        'security_policy' => ['scope' => 'MFA, SSO, sessions, devices', 'owner' => 'security_reviewer', 'enforcement_point' => 'future security profile', 'audit_required' => true, 'override_required' => true],
        'session_policy' => ['scope' => 'session lifetime and revocation', 'owner' => 'security_reviewer', 'enforcement_point' => 'future auth policy layer', 'audit_required' => true, 'override_required' => true],
        'device_policy' => ['scope' => 'trusted devices and posture', 'owner' => 'security_reviewer', 'enforcement_point' => 'future device governance', 'audit_required' => true, 'override_required' => true],
        'api_policy' => ['scope' => 'API keys and service access', 'owner' => 'organization_admin', 'enforcement_point' => 'future API authorization layer', 'audit_required' => true, 'override_required' => true],
        'organization_policy' => ['scope' => 'organization settings and ownership', 'owner' => 'organization_owner', 'enforcement_point' => 'future organization settings layer', 'audit_required' => true, 'override_required' => true],
    ],
    'access_reviews' => [
        'types' => ['organization_access_review', 'workspace_access_review', 'team_access_review', 'api_key_access_review', 'delegated_admin_review', 'emergency_access_review'],
        'lifecycle' => ['scheduled', 'opened', 'reviewed', 'approved', 'revoked', 'archived'],
    ],
    'risk_categories' => [
        'identity_risk' => ['detection_signal' => 'unusual identity lifecycle change', 'severity' => 'high', 'response' => 'review identity and revoke suspicious access', 'audit_trail' => true],
        'access_risk' => ['detection_signal' => 'privileged access drift', 'severity' => 'high', 'response' => 'run access review', 'audit_trail' => true],
        'data_risk' => ['detection_signal' => 'sensitive data export or deletion request', 'severity' => 'high', 'response' => 'approve, scope, and audit action', 'audit_trail' => true],
        'api_risk' => ['detection_signal' => 'API key abuse or unusual usage', 'severity' => 'medium', 'response' => 'rotate key and review policy', 'audit_trail' => true],
        'abuse_risk' => ['detection_signal' => 'abuse spike or throttling pattern', 'severity' => 'medium', 'response' => 'review abuse policy and rate limits', 'audit_trail' => true],
        'billing_risk' => ['detection_signal' => 'billing ownership or payment mismatch', 'severity' => 'medium', 'response' => 'review billing admin and subscription state', 'audit_trail' => true],
        'operational_risk' => ['detection_signal' => 'queue, provider, or domain incident', 'severity' => 'medium', 'response' => 'triage operational owner', 'audit_trail' => true],
        'compliance_risk' => ['detection_signal' => 'missing evidence, export, or retention control', 'severity' => 'high', 'response' => 'open compliance review', 'audit_trail' => true],
    ],
    'audit_events' => ['login_security_events', 'role_changes', 'access_grants', 'access_revocations', 'data_exports', 'data_deletion_requests', 'policy_changes', 'billing_ownership_changes', 'api_key_lifecycle', 'organization_setting_changes', 'emergency_access_usage'],
    'audit_fields' => ['who', 'what', 'when', 'where', 'before_after_snapshot', 'reason', 'correlation_id', 'retention_class'],
    'incident_governance' => [
        'types' => ['security_incident', 'abuse_incident', 'data_incident', 'api_incident', 'billing_incident', 'provider_incident'],
        'lifecycle' => ['detected', 'triaged', 'contained', 'investigated', 'resolved', 'reported', 'archived'],
    ],
    'retention_governance' => [
        'ephemeral_mail_data' => ['retention_class' => 'short_lived', 'deletion_eligible' => true, 'export_eligible' => 'limited', 'audit_required' => true, 'privacy_risk' => 'high'],
        'user_account_data' => ['retention_class' => 'account_lifecycle', 'deletion_eligible' => true, 'export_eligible' => true, 'audit_required' => true, 'privacy_risk' => 'medium'],
        'organization_data' => ['retention_class' => 'contract_lifecycle', 'deletion_eligible' => 'policy_controlled', 'export_eligible' => true, 'audit_required' => true, 'privacy_risk' => 'medium'],
        'audit_logs' => ['retention_class' => 'audit_retained', 'deletion_eligible' => false, 'export_eligible' => 'restricted', 'audit_required' => true, 'privacy_risk' => 'medium'],
        'security_events' => ['retention_class' => 'security_retained', 'deletion_eligible' => false, 'export_eligible' => 'restricted', 'audit_required' => true, 'privacy_risk' => 'medium'],
        'billing_metadata' => ['retention_class' => 'financial_retained', 'deletion_eligible' => 'restricted', 'export_eligible' => true, 'audit_required' => true, 'privacy_risk' => 'medium'],
        'api_logs' => ['retention_class' => 'operational_retained', 'deletion_eligible' => 'policy_controlled', 'export_eligible' => 'aggregate_or_scoped', 'audit_required' => true, 'privacy_risk' => 'medium'],
    ],
    'dashboard_planning' => ['compliance_readiness_score', 'open_access_reviews', 'policy_coverage', 'audit_trail_health', 'retention_policy_coverage', 'export_request_status', 'deletion_request_status', 'incident_status', 'risk_heatmap'],
    'critical_gaps' => [
        'No real policy engine exists.',
        'No access review workflow exists.',
        'No compliance evidence workflow exists.',
        'No organization-scoped audit trail exists.',
        'No formal incident governance workflow exists.',
        'No enterprise compliance dashboard exists.',
    ],
    'step70' => [
        'recommended_next_phase' => 'v1.1 Enterprise Compliance Evidence & Control Mapping Specification',
        'focus' => 'Map governance policies to evidence requirements, control ownership, readiness scoring, and implementation sequencing.',
    ],
];
