<?php

return [
    'readiness_scores' => [
        'authorization_governance' => env('ENTERPRISE_AUTHORIZATION_GOVERNANCE_SCORE', 53),
        'permission_governance' => env('ENTERPRISE_PERMISSION_GOVERNANCE_SCORE', 49),
        'delegated_administration' => env('ENTERPRISE_DELEGATED_ADMIN_SCORE', 50),
        'privileged_access' => env('ENTERPRISE_PRIVILEGED_ACCESS_SCORE', 46),
        'access_review' => env('ENTERPRISE_AUTH_ACCESS_REVIEW_SCORE', 48),
        'separation_of_duties' => env('ENTERPRISE_SOD_SCORE', 44),
    ],
    'authorization_domains' => [
        'authentication' => 'Verify identity; remains separate from authorization decisions.',
        'authorization' => 'Decide what authenticated identities may do.',
        'delegated_authorization' => 'Allow scoped authority granted by eligible owners or admins.',
        'privileged_authorization' => 'Govern high-impact administrative access.',
        'emergency_authorization' => 'Break-glass access with expiry, reason, and audit requirements.',
        'service_authorization' => 'Authorize non-human service, API, automation, and integration identities.',
    ],
    'permission_types' => [
        'direct_permission' => 'Explicit permission assigned to a user, member, or service identity.',
        'role_permission' => 'Permission granted through a future role.',
        'inherited_permission' => 'Permission inherited from organization, workspace, or team membership.',
        'delegated_permission' => 'Permission delegated for a scoped responsibility.',
        'temporary_permission' => 'Time-bound permission with expiry.',
        'emergency_permission' => 'Break-glass permission with strict audit and review.',
    ],
    'permission_lifecycle' => ['requested', 'approved', 'assigned', 'active', 'expiring', 'revoked', 'archived'],
    'access_boundaries' => [
        'personal_boundary' => ['ownership' => 'user', 'visibility' => 'owner', 'control_scope' => 'personal resources', 'escalation_path' => 'support review'],
        'organization_boundary' => ['ownership' => 'organization', 'visibility' => 'owner and admins', 'control_scope' => 'organization resources', 'escalation_path' => 'organization owner'],
        'workspace_boundary' => ['ownership' => 'workspace', 'visibility' => 'workspace admins and scoped members', 'control_scope' => 'workspace resources', 'escalation_path' => 'organization admin'],
        'team_boundary' => ['ownership' => 'team', 'visibility' => 'team leads and scoped members', 'control_scope' => 'team resources', 'escalation_path' => 'workspace admin'],
        'resource_boundary' => ['ownership' => 'resource owner', 'visibility' => 'policy-scoped roles', 'control_scope' => 'single resource', 'escalation_path' => 'resource owner'],
        'administrative_boundary' => ['ownership' => 'platform or organization', 'visibility' => 'admins only', 'control_scope' => 'administration', 'escalation_path' => 'security reviewer'],
        'audit_boundary' => ['ownership' => 'organization or platform', 'visibility' => 'audit roles', 'control_scope' => 'audit evidence', 'escalation_path' => 'compliance reviewer'],
    ],
    'delegated_roles' => [
        'organization_owner' => 'Final authority over organization and ownership changes.',
        'organization_admin' => 'Daily organization administration.',
        'workspace_admin' => 'Workspace-scoped administration.',
        'team_lead' => 'Team-scoped management.',
        'security_reviewer' => 'Security and privileged access review.',
        'compliance_reviewer' => 'Compliance and audit evidence review.',
        'billing_reviewer' => 'Billing and cost visibility review.',
        'auditor' => 'Read-only audit evidence access.',
        'support_operator' => 'Scoped support access with reason and expiry.',
        'guest' => 'Restricted explicit access only.',
    ],
    'privileged_access' => [
        'elevated_access' => 'Expanded permission for admin workflows.',
        'temporary_elevated_access' => 'Time-bound elevation with approval.',
        'emergency_access' => 'Urgent elevation with reason, expiry, and mandatory review.',
        'break_glass_access' => 'Last-resort access path with strongest audit controls.',
        'service_access' => 'Non-human privileged access with owner and rotation controls.',
        'sensitive_resource_access' => 'Access to mail, domain, audit, billing, or security resources.',
    ],
    'certification' => [
        'monthly_review' => 'Frequent review for privileged and emergency access.',
        'quarterly_review' => 'Standard enterprise access certification cadence.',
        'annual_review' => 'Low-risk baseline access review.',
        'event_driven_review' => 'Triggered by role, team, org, incident, or policy changes.',
        'high_risk_review' => 'Triggered by risky access, toxic combinations, or suspicious activity.',
    ],
    'separation_of_duties' => [
        'security_vs_billing' => 'Security reviewers should not silently change billing ownership.',
        'security_vs_compliance' => 'Security operators should not self-certify compliance evidence.',
        'auditor_vs_administrator' => 'Auditors should not mutate systems they audit.',
        'approver_vs_requester' => 'Requesters should not approve their own access.',
        'governance_vs_operations' => 'Governance policy ownership should be separate from routine operations.',
    ],
    'authorization_risks' => [
        'excessive_privilege_risk' => ['description' => 'Access exceeds responsibility.', 'detection' => 'role drift or unused privilege', 'mitigation' => 'certify or revoke', 'audit_required' => true],
        'privilege_escalation_risk' => ['description' => 'Unauthorized elevation.', 'detection' => 'privileged assignment or emergency use', 'mitigation' => 'approval and review', 'audit_required' => true],
        'orphaned_permission_risk' => ['description' => 'Permission without owner or active subject.', 'detection' => 'stale assignment', 'mitigation' => 'revoke and archive', 'audit_required' => true],
        'toxic_combination_risk' => ['description' => 'Conflicting permissions create abuse path.', 'detection' => 'SoD rule violation', 'mitigation' => 'split duties', 'audit_required' => true],
        'delegation_abuse_risk' => ['description' => 'Delegated access used beyond intent.', 'detection' => 'scope or duration anomaly', 'mitigation' => 'expire delegation', 'audit_required' => true],
        'emergency_access_abuse_risk' => ['description' => 'Break-glass access used without justification.', 'detection' => 'missing reason or repeated use', 'mitigation' => 'mandatory review', 'audit_required' => true],
    ],
    'access_reviews' => [
        'types' => ['user_access_review', 'organization_access_review', 'workspace_access_review', 'team_access_review', 'api_access_review', 'delegated_access_review'],
        'lifecycle' => ['scheduled', 'opened', 'reviewed', 'approved', 'revoked', 'archived'],
    ],
    'service_authorization' => [
        'internal_services' => 'Internal application services with least privilege and owner.',
        'automation_services' => 'Automation identities with scoped execution rights.',
        'integration_services' => 'Integration identities with connector-specific boundaries.',
        'api_services' => 'API service identities with key lifecycle governance.',
        'enterprise_connectors' => 'Future enterprise connectors with explicit authorization boundaries.',
    ],
    'audit_events' => ['permission_request', 'permission_approval', 'permission_assignment', 'permission_revocation', 'delegation_grant', 'delegation_removal', 'emergency_access_usage', 'break_glass_usage', 'service_access_change', 'access_certification'],
    'policy_enforcement_readiness' => [
        'policy_based_authorization' => 'Future authorization based on explicit policy rules.',
        'context_aware_authorization' => 'Future decisions using identity, resource, device, and session context.',
        'risk_based_authorization' => 'Future decisions based on risk signals.',
        'attribute_based_authorization' => 'Future ABAC support using attributes and claims.',
        'enterprise_governance_policies' => 'Future organization-owned governance policies.',
    ],
    'critical_gaps' => [
        'No enterprise authorization policy engine exists.',
        'No organization-scoped permission model exists.',
        'No delegated administration implementation exists.',
        'No privileged access workflow exists.',
        'No access certification workflow exists.',
        'No separation-of-duties enforcement exists.',
    ],
    'step73' => [
        'recommended_next_phase' => 'v1.1 Enterprise Policy Enforcement & Access Certification Specification',
        'focus' => 'Specify future enforcement points, certification workflows, approval controls, and audit evidence without changing current RBAC.',
    ],
];
