<?php

return [
    'readiness_scores' => [
        'identity_governance' => env('ENTERPRISE_IDENTITY_GOVERNANCE_SCORE', 52),
        'enterprise_sso' => env('ENTERPRISE_SSO_SCORE', 44),
        'federation' => env('ENTERPRISE_FEDERATION_SCORE', 46),
        'mfa_governance' => env('ENTERPRISE_MFA_GOVERNANCE_SCORE', 48),
        'session_governance' => env('ENTERPRISE_SESSION_GOVERNANCE_SCORE', 50),
        'device_governance' => env('ENTERPRISE_DEVICE_GOVERNANCE_SCORE', 42),
    ],
    'identity_sources' => [
        'local_identity' => 'Application-owned identity for existing users and personal accounts.',
        'organization_identity' => 'Future organization-owned identity relationship for enterprise accounts.',
        'federated_identity' => 'Future identity delegated to SAML, OIDC, or OAuth federation provider.',
        'service_identity' => 'Future non-human identity for service-to-service and automation workflows.',
    ],
    'sso' => [
        'protocols' => ['saml_2_0', 'openid_connect', 'oauth_federation'],
        'providers' => ['microsoft_entra_id', 'okta', 'google_workspace'],
        'support_model' => 'Future per-organization identity provider configuration with metadata, claim mapping, and safe rollback.',
    ],
    'federation' => [
        'identity_federation' => 'Trust external identity provider authentication while retaining local authorization controls.',
        'trust_relationships' => 'Per-organization trust configuration with issuer, audience, signing material, and expiry tracking.',
        'identity_mapping' => 'Map external subject identifiers to future organization memberships.',
        'group_mapping' => 'Map provider groups to organization, workspace, or team roles.',
        'role_mapping' => 'Translate external claims into bounded future roles.',
        'claim_mapping' => 'Normalize email, subject, groups, name, tenant, and assurance claims.',
    ],
    'identity_lifecycle' => [
        'states' => ['invited', 'pending_activation', 'active', 'suspended', 'locked', 'disabled', 'archived'],
        'transitions' => [
            'invited_to_pending_activation',
            'pending_activation_to_active',
            'active_to_suspended',
            'suspended_to_active',
            'active_to_locked',
            'locked_to_active',
            'active_to_disabled',
            'disabled_to_archived',
        ],
    ],
    'access_governance' => [
        'domains' => ['access_request', 'access_approval', 'access_certification', 'access_revocation', 'emergency_access', 'temporary_access'],
        'lifecycle' => ['requested', 'reviewed', 'approved', 'provisioned', 'certified', 'revoked', 'archived'],
    ],
    'mfa_governance' => [
        'totp' => 'Future time-based one-time-password support.',
        'security_keys' => 'Future phishing-resistant hardware-backed authentication.',
        'passkeys' => 'Future platform authenticator and synced passkey readiness.',
        'backup_codes' => 'Future recovery path with strict lifecycle controls.',
        'risk_based_mfa' => 'Future step-up authentication based on session, device, and identity risk.',
    ],
    'session_governance' => [
        'session_ownership' => 'Sessions should belong to user identity and future organization context.',
        'session_policies' => 'Future lifetime, idle timeout, and assurance rules.',
        'session_revocation' => 'Future user, admin, and security reviewer revocation paths.',
        'concurrent_session_limits' => 'Future organization policy for session count limits.',
        'session_review' => 'Future review of active, risky, and privileged sessions.',
        'high_risk_session_detection' => 'Future signals for unfamiliar device, location, impossible travel, and privilege changes.',
    ],
    'device_governance' => [
        'registered_device' => 'Known device registered to user or organization context.',
        'trusted_device' => 'Device trusted by policy after verification.',
        'managed_device' => 'Device governed by enterprise policy.',
        'unmanaged_device' => 'Device without enterprise controls.',
        'risky_device' => 'Device with suspicious posture or behavior.',
        'revoked_device' => 'Device no longer allowed for enterprise access.',
    ],
    'identity_risks' => [
        'credential_risk' => ['description' => 'Compromised or weak credential risk.', 'signals' => ['failed_logins', 'password_reuse', 'breach_indicator'], 'audit_required' => true, 'action' => 'force reset and review access'],
        'session_risk' => ['description' => 'Suspicious or stale session risk.', 'signals' => ['new_location', 'high_privilege_session', 'long_lived_session'], 'audit_required' => true, 'action' => 'revoke session and require MFA'],
        'device_risk' => ['description' => 'Unknown or unsafe device risk.', 'signals' => ['unmanaged_device', 'revoked_device', 'risky_device'], 'audit_required' => true, 'action' => 'block or step-up authentication'],
        'federation_risk' => ['description' => 'Identity provider trust or mapping risk.', 'signals' => ['metadata_expiry', 'claim_mismatch', 'issuer_change'], 'audit_required' => true, 'action' => 'pause federation and review trust'],
        'insider_risk' => ['description' => 'Authorized user misuse risk.', 'signals' => ['bulk_export', 'privilege_change', 'unusual_access'], 'audit_required' => true, 'action' => 'open access review'],
        'privilege_risk' => ['description' => 'Excessive permission or role drift.', 'signals' => ['stale_admin', 'unreviewed_role', 'emergency_access'], 'audit_required' => true, 'action' => 'certify or revoke access'],
        'api_identity_risk' => ['description' => 'Service or API identity misuse.', 'signals' => ['key_spike', 'old_key', 'unowned_key'], 'audit_required' => true, 'action' => 'rotate key and review owner'],
    ],
    'role_governance' => [
        'organization_owner' => 'Owns identity provider, security policy, billing identity, and final authority.',
        'organization_admin' => 'Manages members and routine identity lifecycle.',
        'workspace_admin' => 'Manages scoped workspace access.',
        'team_lead' => 'Coordinates team access and reviews.',
        'member' => 'Uses assigned resources.',
        'guest' => 'Uses explicitly granted limited access.',
        'security_reviewer' => 'Reviews identity, access, session, and device risk.',
        'compliance_reviewer' => 'Reviews evidence, access certification, and audit exports.',
        'auditor' => 'Reads scoped audit evidence only.',
        'service_identity' => 'Non-human identity with explicit ownership and rotation.',
    ],
    'audit_events' => ['login', 'logout', 'mfa_enrollment', 'mfa_removal', 'sso_login', 'identity_provisioning', 'identity_suspension', 'role_assignment', 'access_approval', 'session_revocation', 'device_registration', 'device_revocation'],
    'provisioning' => [
        'manual_provisioning' => 'Human-managed invite, activation, suspension, and removal.',
        'automated_provisioning' => 'Future rules-based provisioning without external federation dependency.',
        'federated_provisioning' => 'Future identity provider driven membership lifecycle.',
        'just_in_time_provisioning' => 'Future first-login membership creation based on trusted claims.',
        'scim_readiness' => 'Future standardized identity lifecycle API readiness.',
    ],
    'critical_gaps' => [
        'No SAML or OIDC implementation exists.',
        'No enterprise MFA governance implementation exists.',
        'No identity provider trust model exists.',
        'No SCIM or automated provisioning exists.',
        'No session or device governance implementation exists.',
        'No identity risk review workflow exists.',
    ],
    'step71' => [
        'recommended_next_phase' => 'v1.1 Enterprise Provisioning & Lifecycle Control Specification',
        'focus' => 'Specify SCIM readiness, JIT provisioning, lifecycle controls, deprovisioning safety, and identity audit evidence.',
    ],
];
