<?php

return [
    'readiness_scores' => [
        'provisioning' => env('ENTERPRISE_PROVISIONING_SCORE', 45),
        'lifecycle_governance' => env('ENTERPRISE_LIFECYCLE_GOVERNANCE_SCORE', 50),
        'joiner_mover_leaver' => env('ENTERPRISE_JML_SCORE', 48),
        'organization_onboarding' => env('ENTERPRISE_ORG_ONBOARDING_SCORE', 52),
        'scim' => env('ENTERPRISE_SCIM_READINESS_SCORE', 38),
        'lifecycle_audit' => env('ENTERPRISE_LIFECYCLE_AUDIT_SCORE', 55),
    ],
    'provisioning_domains' => [
        'identity_provisioning' => 'Future lifecycle for creating, activating, suspending, disabling, and archiving identities.',
        'membership_provisioning' => 'Future lifecycle for assigning users to organizations, workspaces, teams, and roles.',
        'organization_provisioning' => 'Future lifecycle for onboarding and configuring enterprise organizations.',
        'workspace_provisioning' => 'Future lifecycle for creating and governing workspace boundaries.',
        'team_provisioning' => 'Future lifecycle for creating and governing teams.',
        'api_identity_provisioning' => 'Future lifecycle for user, organization, workspace, and service API identities.',
    ],
    'joiner_mover_leaver' => [
        'joiner' => ['invited', 'pending', 'activated', 'onboarded'],
        'mover' => ['requested', 'approved', 'transitioned', 'validated'],
        'leaver' => ['scheduled', 'suspended', 'revoked', 'archived'],
    ],
    'access_lifecycle' => [
        'access_request',
        'access_approval',
        'access_assignment',
        'access_certification',
        'access_revocation',
        'access_expiration',
        'emergency_access',
    ],
    'organization_onboarding' => [
        'self_service_organization' => 'Customer-led setup with safe defaults and limited enterprise controls.',
        'assisted_organization' => 'Guided setup by support or customer success with governance checklist.',
        'enterprise_contract_organization' => 'Contract-backed setup with security, compliance, billing, and identity review.',
    ],
    'organization_offboarding' => [
        'voluntary_closure' => ['data_ownership' => 'organization_owned', 'export_right' => true, 'retention_effect' => 'standard_retention', 'audit_required' => true],
        'contract_expiration' => ['data_ownership' => 'organization_owned', 'export_right' => true, 'retention_effect' => 'contract_retention', 'audit_required' => true],
        'security_suspension' => ['data_ownership' => 'organization_owned', 'export_right' => 'restricted', 'retention_effect' => 'security_hold', 'audit_required' => true],
        'compliance_closure' => ['data_ownership' => 'organization_owned', 'export_right' => 'approved_only', 'retention_effect' => 'compliance_hold', 'audit_required' => true],
        'forced_termination' => ['data_ownership' => 'organization_owned', 'export_right' => 'restricted', 'retention_effect' => 'legal_or_policy_review', 'audit_required' => true],
    ],
    'workspace_lifecycle' => ['draft', 'active', 'suspended', 'archived', 'deleted'],
    'team_lifecycle' => ['proposed', 'active', 'merged', 'suspended', 'archived'],
    'membership_governance' => [
        'invitation_governance' => 'Control who can invite, approve, expire, and resend invitations.',
        'approval_governance' => 'Require approval for privileged roles, guests, and delegated access.',
        'role_transition_governance' => 'Require review for role, workspace, or team moves.',
        'suspension_governance' => 'Define temporary suspension, reason capture, and reinstatement controls.',
        'removal_governance' => 'Define revocation, audit retention, seat release, and export rights.',
    ],
    'scim_readiness' => [
        'user_lifecycle' => 'Future standardized create, update, suspend, disable, and delete identity lifecycle.',
        'group_lifecycle' => 'Future group creation, update, membership, and removal lifecycle.',
        'membership_sync' => 'Future mapping from IdP groups to organization, workspace, team, and roles.',
        'deprovisioning' => 'Future automatic access revocation and lifecycle audit safety.',
        'attribute_mapping' => 'Future mapping for email, name, external id, status, department, and manager.',
        'role_mapping' => 'Future bounded mapping from IdP groups or attributes to internal roles.',
    ],
    'provisioning_risks' => [
        'over_provisioning_risk' => ['description' => 'Too much access granted.', 'detection' => 'role drift or excessive group mapping', 'governance_required' => true, 'audit_required' => true],
        'under_provisioning_risk' => ['description' => 'Required access missing.', 'detection' => 'failed workflow or access request backlog', 'governance_required' => true, 'audit_required' => true],
        'privilege_escalation_risk' => ['description' => 'Unauthorized role elevation.', 'detection' => 'privileged role assignment or emergency access', 'governance_required' => true, 'audit_required' => true],
        'stale_access_risk' => ['description' => 'Old access remains active.', 'detection' => 'inactive member or expired assignment', 'governance_required' => true, 'audit_required' => true],
        'orphaned_identity_risk' => ['description' => 'Identity without owner or membership.', 'detection' => 'unlinked user or service identity', 'governance_required' => true, 'audit_required' => true],
        'automation_failure_risk' => ['description' => 'Lifecycle automation fails or partially completes.', 'detection' => 'failed workflow or inconsistent state', 'governance_required' => true, 'audit_required' => true],
    ],
    'lifecycle_audit_events' => ['invitation', 'acceptance', 'provisioning', 'role_change', 'team_change', 'workspace_change', 'suspension', 'revocation', 'offboarding', 'organization_closure'],
    'automation_readiness' => [
        'auto_provisioning' => 'Future automatic creation and assignment from trusted sources.',
        'auto_deprovisioning' => 'Future automatic suspension, revocation, and archival.',
        'lifecycle_workflows' => 'Future orchestrated joiner, mover, and leaver workflows.',
        'approval_workflows' => 'Future approval paths for privileged or sensitive changes.',
        'access_expiration_workflows' => 'Future expiry and renewal of temporary access.',
        'compliance_workflows' => 'Future evidence-ready lifecycle controls.',
    ],
    'critical_gaps' => [
        'No SCIM implementation exists.',
        'No provisioning workflow engine exists.',
        'No joiner/mover/leaver lifecycle implementation exists.',
        'No deprovisioning safety workflow exists.',
        'No access expiration workflow exists.',
        'No lifecycle audit evidence workflow exists.',
    ],
    'step72' => [
        'recommended_next_phase' => 'v1.1 Enterprise Audit Evidence & Reporting Specification',
        'focus' => 'Specify lifecycle evidence, audit reports, compliance exports, reviewer workflows, and non-breaking reporting architecture.',
    ],
];
