<?php

return [
    'readiness' => [
        'https_required' => env('PRODUCTION_HTTPS_REQUIRED', true),
        'allowed_queue_drivers' => array_filter(array_map(
            'trim',
            explode(',', env('PRODUCTION_ALLOWED_QUEUE_DRIVERS', 'database,redis,sqs,sync')),
        )),
        'allow_log_mailer_in_production' => env('PRODUCTION_ALLOW_LOG_MAILER', false),
    ],
    'release' => [
        'target' => env('RELEASE_TARGET', 'rc1'),
        'block_on_debug' => env('RELEASE_BLOCK_ON_DEBUG', true),
        'block_on_missing_app_key' => env('RELEASE_BLOCK_ON_MISSING_APP_KEY', true),
        'block_on_unwritable_storage' => env('RELEASE_BLOCK_ON_UNWRITABLE_STORAGE', true),
        'warn_on_http_url' => env('RELEASE_WARN_ON_HTTP_URL', true),
        'warn_on_sync_queue' => env('RELEASE_WARN_ON_SYNC_QUEUE', true),
        'warn_on_log_mailer' => env('RELEASE_WARN_ON_LOG_MAILER', true),
    ],
    'deployment' => [
        'required_writable_paths' => [
            storage_path(),
            storage_path('app'),
            storage_path('framework'),
            storage_path('logs'),
            base_path('bootstrap/cache'),
        ],
        'recommended_cache_store' => env('PRODUCTION_RECOMMENDED_CACHE_STORE', 'database'),
        'recommended_session_driver' => env('PRODUCTION_RECOMMENDED_SESSION_DRIVER', 'database'),
        'checklists' => [
            'shared_hosting' => env('DEPLOYMENT_SHARED_HOSTING_CHECKLIST', true),
            'vps' => env('DEPLOYMENT_VPS_CHECKLIST', true),
            'queue_workers' => env('DEPLOYMENT_QUEUE_WORKER_CHECKLIST', true),
            'scheduler' => env('DEPLOYMENT_SCHEDULER_CHECKLIST', true),
        ],
    ],
    'monitoring' => [
        'health_route' => '/health',
        'status_route' => '/status',
        'up_route' => '/up',
        'operations_metrics_required' => env('PRODUCTION_OPERATIONS_METRICS_REQUIRED', false),
    ],
    'health' => [
        'logging_enabled' => env('SYSTEM_HEALTH_LOGGING_ENABLED', true),
        'schedule_enabled' => env('SYSTEM_HEALTH_SCHEDULE_ENABLED', false),
        'schedule_frequency' => env('SYSTEM_HEALTH_SCHEDULE_FREQUENCY', 'hourly'),
    ],
    'backup' => [
        'destination_disk' => env('BACKUP_DESTINATION_DISK', 'local'),
        'paths' => [
            storage_path('app'),
            database_path(),
        ],
        'restore_prerequisites_documented' => env('BACKUP_RESTORE_PREREQUISITES_DOCUMENTED', true),
        'retention_guidance_documented' => env('BACKUP_RETENTION_GUIDANCE_DOCUMENTED', true),
    ],
    'error_tracking' => [
        'enabled' => env('ERROR_TRACKING_ENABLED', true),
        'provider' => env('ERROR_TRACKING_PROVIDER', 'log'),
    ],
    'launch' => [
        'target' => env('GO_LIVE_TARGET', 'v1'),
        'require_monitoring_ready' => env('GO_LIVE_REQUIRE_MONITORING_READY', true),
        'require_backup_ready' => env('GO_LIVE_REQUIRE_BACKUP_READY', true),
        'require_provider_onboarding_docs' => env('GO_LIVE_REQUIRE_PROVIDER_DOCS', true),
        'require_domain_onboarding_docs' => env('GO_LIVE_REQUIRE_DOMAIN_DOCS', true),
    ],
    'rollback' => [
        'require_backup_ready' => env('ROLLBACK_REQUIRE_BACKUP_READY', true),
        'require_deployment_notes' => env('ROLLBACK_REQUIRE_DEPLOYMENT_NOTES', true),
        'require_restore_prerequisites' => env('ROLLBACK_REQUIRE_RESTORE_PREREQUISITES', true),
        'documentation_path' => env('ROLLBACK_DOCUMENTATION_PATH', 'docs/deployment/shared-hosting.md'),
    ],
    'onboarding' => [
        'providers' => [
            'mailgun',
            'postmark',
            'amazon_ses',
        ],
        'domains' => [
            'domain_pool_ready' => true,
            'dns_verification_future_ready' => true,
            'provider_mapping_checklist' => true,
        ],
    ],
    'first_live_validation' => [
        'require_app_env_production' => env('FIRST_LIVE_REQUIRE_PRODUCTION_ENV', true),
        'warn_on_sync_queue' => env('FIRST_LIVE_WARN_ON_SYNC_QUEUE', true),
        'warn_on_log_mailer' => env('FIRST_LIVE_WARN_ON_LOG_MAILER', true),
        'require_installer_lock' => env('FIRST_LIVE_REQUIRE_INSTALLER_LOCK', true),
    ],
    'smoke_tests' => [
        'routes' => [
            'home',
            'health',
            'status',
            'inbox.index',
            'sitemap',
            'robots',
            'api.v1.ping',
            'admin.index',
            'installer.index',
        ],
    ],
    'server_readiness' => [
        'minimum_php_version' => env('FIRST_LIVE_MINIMUM_PHP_VERSION', '8.2.0'),
        'required_extensions' => array_filter(array_map(
            'trim',
            explode(',', env('FIRST_LIVE_REQUIRED_EXTENSIONS', 'ctype,curl,dom,fileinfo,filter,hash,mbstring,openssl,pcre,pdo,session,tokenizer,xml')),
        )),
        'scheduler_required' => env('FIRST_LIVE_SCHEDULER_REQUIRED', false),
        'queue_worker_required' => env('FIRST_LIVE_QUEUE_WORKER_REQUIRED', false),
    ],
    'deployment_readiness' => [
        'queue' => [
            'require_worker_driver' => env('DEPLOYMENT_REQUIRE_WORKER_DRIVER', true),
            'workers_documented' => env('DEPLOYMENT_QUEUE_WORKERS_DOCUMENTED', true),
            'restart_strategy_documented' => env('DEPLOYMENT_QUEUE_RESTART_DOCUMENTED', true),
            'failed_jobs_strategy_documented' => env('DEPLOYMENT_FAILED_JOBS_DOCUMENTED', true),
            'supervisor_compatibility_documented' => env('DEPLOYMENT_SUPERVISOR_NOTES_DOCUMENTED', true),
        ],
        'scheduler' => [
            'cron_requirements_documented' => env('DEPLOYMENT_CRON_DOCUMENTED', true),
            'scheduler_ready' => env('DEPLOYMENT_SCHEDULER_READY', true),
            'cleanup_schedule_documented' => env('DEPLOYMENT_CLEANUP_SCHEDULE_DOCUMENTED', true),
            'monitoring_schedule_documented' => env('DEPLOYMENT_MONITORING_SCHEDULE_DOCUMENTED', true),
        ],
        'provider' => [
            'name' => env('DEPLOYMENT_PROVIDER', 'mailgun'),
            'rollback_documented' => env('DEPLOYMENT_PROVIDER_ROLLBACK_DOCUMENTED', true),
        ],
        'domain' => [
            'mx_checklist' => env('DEPLOYMENT_DOMAIN_MX_CHECKLIST', true),
            'spf_checklist' => env('DEPLOYMENT_DOMAIN_SPF_CHECKLIST', true),
            'dkim_checklist' => env('DEPLOYMENT_DOMAIN_DKIM_CHECKLIST', true),
            'dmarc_checklist' => env('DEPLOYMENT_DOMAIN_DMARC_CHECKLIST', true),
        ],
    ],
    'rc3' => [
        'target' => env('RC3_CERTIFICATION_TARGET', 'rc3'),
        'provider' => env('RC3_CERTIFICATION_PROVIDER', 'mailgun'),
        'domain' => env('RC3_CERTIFICATION_DOMAIN'),
        'mailbox' => env('RC3_CERTIFICATION_MAILBOX'),
        'require_active_domain' => env('RC3_REQUIRE_ACTIVE_DOMAIN', true),
        'require_installer_lock' => env('RC3_REQUIRE_INSTALLER_LOCK', true),
        'require_scheduler_ready' => env('RC3_REQUIRE_SCHEDULER_READY', false),
        'require_queue_worker_ready' => env('RC3_REQUIRE_QUEUE_WORKER_READY', false),
        'blocker_threshold' => env('RC3_BLOCKER_THRESHOLD', 1),
        'warning_threshold' => env('RC3_WARNING_THRESHOLD', 1),
        'launch_certification' => [
            'security' => true,
            'infrastructure' => true,
            'provider' => true,
            'domain' => true,
            'queue' => true,
            'billing' => true,
            'operations' => true,
        ],
    ],
    'public_beta' => [
        'target' => env('PUBLIC_BETA_TARGET', 'public-beta'),
        'require_rc3_certified' => env('PUBLIC_BETA_REQUIRE_RC3_CERTIFIED', true),
        'onboarding' => [
            'require_installer_complete' => env('PUBLIC_BETA_REQUIRE_INSTALLER_COMPLETE', true),
            'require_registration' => env('PUBLIC_BETA_REQUIRE_REGISTRATION', true),
            'require_login' => env('PUBLIC_BETA_REQUIRE_LOGIN', true),
            'require_inbox' => env('PUBLIC_BETA_REQUIRE_INBOX', true),
            'require_localization' => env('PUBLIC_BETA_REQUIRE_LOCALIZATION', true),
            'require_domain_ready' => env('PUBLIC_BETA_REQUIRE_DOMAIN_READY', true),
            'require_provider_ready' => env('PUBLIC_BETA_REQUIRE_PROVIDER_READY', true),
        ],
        'support' => [
            'runbooks_documented' => env('PUBLIC_BETA_RUNBOOKS_DOCUMENTED', true),
            'escalation_paths_documented' => env('PUBLIC_BETA_ESCALATION_PATHS_DOCUMENTED', true),
            'troubleshooting_guidance_documented' => env('PUBLIC_BETA_TROUBLESHOOTING_DOCUMENTED', true),
            'incident_process_required' => env('PUBLIC_BETA_INCIDENT_PROCESS_REQUIRED', true),
            'monitoring_process_required' => env('PUBLIC_BETA_MONITORING_PROCESS_REQUIRED', true),
        ],
        'feedback' => [
            'collection_documented' => env('PUBLIC_BETA_FEEDBACK_COLLECTION_DOCUMENTED', true),
            'issue_intake_documented' => env('PUBLIC_BETA_ISSUE_INTAKE_DOCUMENTED', true),
            'operational_response_documented' => env('PUBLIC_BETA_OPERATIONAL_RESPONSE_DOCUMENTED', true),
        ],
    ],
    'v1_launch' => [
        'target' => env('V1_LAUNCH_TARGET', 'v1.0.0'),
        'require_public_beta_certified' => env('V1_REQUIRE_PUBLIC_BETA_CERTIFIED', true),
        'require_rc3_certified' => env('V1_REQUIRE_RC3_CERTIFIED', true),
        'require_go_live_ready' => env('V1_REQUIRE_GO_LIVE_READY', true),
        'sign_off_categories' => [
            'security',
            'infrastructure',
            'mail_providers',
            'domains',
            'billing',
            'api',
            'public_inbox',
            'admin_operations',
            'monitoring',
            'rollback',
            'support_readiness',
        ],
        'monitoring_24h' => [
            'queue_backlog_warning' => env('V1_MONITOR_QUEUE_BACKLOG_WARNING', 100),
            'provider_failures_warning' => env('V1_MONITOR_PROVIDER_FAILURES_WARNING', 5),
            'webhook_failures_warning' => env('V1_MONITOR_WEBHOOK_FAILURES_WARNING', 10),
            'inbox_polling_errors_warning' => env('V1_MONITOR_INBOX_POLLING_ERRORS_WARNING', 10),
            'abuse_spikes_warning' => env('V1_MONITOR_ABUSE_SPIKES_WARNING', 25),
            'billing_webhook_failures_warning' => env('V1_MONITOR_BILLING_FAILURES_WARNING', 1),
            'api_errors_warning' => env('V1_MONITOR_API_ERRORS_WARNING', 25),
            'incident_count_warning' => env('V1_MONITOR_INCIDENT_COUNT_WARNING', 1),
        ],
        'rollback_triggers' => [
            'critical_incident_open' => true,
            'queue_backlog_critical' => true,
            'provider_failure_spike' => true,
            'mail_reception_failure' => true,
            'security_regression' => true,
        ],
    ],
    'first_24_hours' => [
        'window_hours' => env('FIRST_24H_WINDOW_HOURS', 24),
        'thresholds' => [
            'queue_pending_warning' => env('FIRST_24H_QUEUE_PENDING_WARNING', 100),
            'queue_pending_critical' => env('FIRST_24H_QUEUE_PENDING_CRITICAL', 500),
            'queue_failed_warning' => env('FIRST_24H_QUEUE_FAILED_WARNING', 1),
            'queue_failed_critical' => env('FIRST_24H_QUEUE_FAILED_CRITICAL', 10),
            'provider_failures_warning' => env('FIRST_24H_PROVIDER_FAILURES_WARNING', 5),
            'provider_failures_critical' => env('FIRST_24H_PROVIDER_FAILURES_CRITICAL', 20),
            'webhook_failures_warning' => env('FIRST_24H_WEBHOOK_FAILURES_WARNING', 10),
            'webhook_failures_critical' => env('FIRST_24H_WEBHOOK_FAILURES_CRITICAL', 40),
            'inbox_failures_warning' => env('FIRST_24H_INBOX_FAILURES_WARNING', 10),
            'inbox_failures_critical' => env('FIRST_24H_INBOX_FAILURES_CRITICAL', 30),
            'billing_failures_warning' => env('FIRST_24H_BILLING_FAILURES_WARNING', 1),
            'api_failures_warning' => env('FIRST_24H_API_FAILURES_WARNING', 25),
            'incident_warning' => env('FIRST_24H_INCIDENT_WARNING', 1),
            'incident_critical' => env('FIRST_24H_INCIDENT_CRITICAL', 1),
        ],
        'escalation' => [
            'high_incidents' => env('FIRST_24H_ESCALATE_HIGH_INCIDENTS', 1),
            'critical_incidents' => env('FIRST_24H_ESCALATE_CRITICAL_INCIDENTS', 1),
        ],
        'rollback' => [
            'critical_incident_threshold' => env('FIRST_24H_ROLLBACK_CRITICAL_INCIDENTS', 1),
            'queue_pending_threshold' => env('FIRST_24H_ROLLBACK_QUEUE_PENDING', 500),
            'queue_failed_threshold' => env('FIRST_24H_ROLLBACK_QUEUE_FAILED', 10),
            'provider_failure_threshold' => env('FIRST_24H_ROLLBACK_PROVIDER_FAILURES', 20),
            'inbox_failure_threshold' => env('FIRST_24H_ROLLBACK_INBOX_FAILURES', 30),
        ],
        'review' => [
            'health_checks_required' => env('FIRST_24H_HEALTH_CHECKS_REQUIRED', true),
            'queue_metrics_required' => env('FIRST_24H_QUEUE_METRICS_REQUIRED', true),
            'provider_metrics_required' => env('FIRST_24H_PROVIDER_METRICS_REQUIRED', true),
            'billing_metrics_required' => env('FIRST_24H_BILLING_METRICS_REQUIRED', true),
            'api_metrics_required' => env('FIRST_24H_API_METRICS_REQUIRED', true),
            'operations_metrics_required' => env('FIRST_24H_OPERATIONS_METRICS_REQUIRED', true),
            'alert_readiness' => env('FIRST_24H_ALERT_READINESS', true),
            'incident_readiness' => env('FIRST_24H_INCIDENT_READINESS', true),
        ],
    ],
];
